version: "3.8"
#You can set default values for environment variables using a .env file,
#which Compose automatically looks for in project directory (parent folder of your Compose file).
#Values set in the shell environment override those set in the .env file.
services:
  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      #ports=HOST:CONTAINER
      - "32000:3306"
    environment:
      - POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD}

  webapp:
    build:
      context: .
      dockerfile: ./Bakerapp/Dockerfile
    env_file: .env
    links:
      - db
    ports:
      #ports=HOST:CONTAINER
      - "8000:8000"
    depends_on:
      - "db"
