version: "3.8"
services:
  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      #ports=HOST:CONTAINER
      - "32000:3306"
    environment:
      - POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD}

  webapp:
    build:
      context: .
      dockerfile: ./Bakerapp/Dockerfile
    env_file: .env
    links:
      - db
    ports:
      #ports=HOST:CONTAINER
      - "8000:8000"
    depends_on:
      - "db"
